title: MatGL
email: ongsp@ucsd.edu
description: >- # this means to ignore newlines until "baseurl:"
  A graph deep learning library for materials science.
baseurl: "/"
url: "https://matgl.ai"
# twitter_username: jekyllrb
github_username:  materialsvirtuallab

# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

aux_links:
  "MatGL on GitHub":
    - "https://github.com/materialsvirtuallab/matgl"
  "Materials Virtual Lab":
    - "https://materialsvirtuallab.org"