name: Linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade setuptools>=58.0.3
        pip install --upgrade pip
        pip install --quiet -r requirements-ci.txt
    - name: mypy
      run: |
        mypy megnet
    - name: flake8
      run: |
        flake8 --count --show-source --statistics megnet
        # exit-zero treats all errors as warnings.
        flake8 --count --exit-zero --max-complexity=20 --statistics megnet
    - name: pylint
      run: |
        pylint megnet
    - name: pydocstyle
      run: |
        pydocstyle --count megnet
